"""add rating field in Ticket model

Revision ID: 1564dce09cf3
Revises: ab0f75522994
Create Date: 2023-02-27 01:54:10.022441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1564dce09cf3'
down_revision = 'ab0f75522994'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket', 'rating')
    # ### end Alembic commands ###
